### PR TITLE
Issue 5 cases index page

### PR DESCRIPTION
**Pull request by naseerkassar**

### CODE REVIEW

**Comment by Moeriki** [comment]
- [ ] Not all commits follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
- [ ] Branch needs rebase

**Comment by naseerkassar** [comment]
good morning Dieter i have solved the errors rebased the branch and committed the changes please check out the new version of the code  and if there is any issue please let me know

**Comment by Moeriki** [comment]
There is a merge errors in the last commit and an unused variable.

You can run `yarn lint` to uncover both.

**Comment by naseerkassar** [comment]
it doesn't work for me i keep getting command not found

**Comment by Moeriki** [comment]
I resolved the conflicts and squash merged the branch. You can delete the branch locally now.

**Comment by naseerkassar** [comment]
thanks i found the problem it was un committed changes in case template but you was already resolved the conflicts and squash merged the branch.
thanks it is locally deleted it now

**Pull request closed without merging**
